<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-84KGOP9" ignored="0" name="Facebook Sign In Test" tests="3" failures="2" timestamp="16 Jan 2019 04:57:45 GMT" time="115.937" errors="0">
  <testcase name="facebookLogin" time="60.069" classname="com.pge.hybrid.testcases.facebooksuite.FacebookTest">
    <failure type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
at com.pge.hybrid.driver.DriverScript.executeKeywords(DriverScript.java:47)
at com.pge.hybrid.testcases.facebooksuite.FacebookTest.facebookLogin(FacebookTest.java:24)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AssertionError: The following asserts failed:
Object Not Found photo_vid_xpath
at com.pge.hybrid.keywords.GenericKeywords.reportFailure(GenericKeywords.java:374)
at com.pge.hybrid.keywords.GenericKeywords.getObject(GenericKeywords.java:307)
at com.pge.hybrid.keywords.GenericKeywords.click(GenericKeywords.java:150)
... 26 more
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- facebookLogin -->
  <testcase name="facebookLogin" time="0.0" classname="com.pge.hybrid.testcases.facebooksuite.FacebookTest">
    <skipped/>
  </testcase> <!-- facebookLogin -->
  <testcase name="AppScanSite" time="53.167" classname="com.pge.hybrid.testcases.facebooksuite.FacebookTest">
    <failure type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
at com.pge.hybrid.driver.DriverScript.executeKeywords(DriverScript.java:47)
at com.pge.hybrid.testcases.facebooksuite.FacebookTest.AppScanSite(FacebookTest.java:37)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AssertionError: The following asserts failed:
Object Not Found SignIn_xpath
at com.pge.hybrid.keywords.GenericKeywords.reportFailure(GenericKeywords.java:374)
at com.pge.hybrid.keywords.GenericKeywords.getObject(GenericKeywords.java:307)
at com.pge.hybrid.keywords.GenericKeywords.click(GenericKeywords.java:150)
... 26 more
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- AppScanSite -->
</testsuite> <!-- Facebook Sign In Test -->
