<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="5" failed="4" ignored="0" total="9" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Yahoo Suite" duration-ms="34831" started-at="2019-01-16T04:54:14Z" finished-at="2019-01-16T04:54:49Z">
    <groups>
    </groups>
    <test name="Yahoo Sign up Test" duration-ms="2389" started-at="2019-01-16T04:54:14Z" finished-at="2019-01-16T04:54:16Z">
      <class name="com.pge.hybrid.testcases.yahoosuite.YahooSignUp">
        <test-method status="PASS" signature="init()[pri:0, instance:com.pge.hybrid.testcases.yahoosuite.YahooSignUp@3aa9e816]" name="init" is-config="true" duration-ms="1192" started-at="2019-01-16T04:54:14Z" finished-at="2019-01-16T04:54:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="initTest()[pri:0, instance:com.pge.hybrid.testcases.yahoosuite.YahooSignUp@3aa9e816]" name="initTest" is-config="true" duration-ms="259" started-at="2019-01-16T04:54:15Z" finished-at="2019-01-16T04:54:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initTest -->
        <test-method status="SKIP" signature="YahooSignUp(java.util.Hashtable)[pri:0, instance:com.pge.hybrid.testcases.yahoosuite.YahooSignUp@3aa9e816]" name="YahooSignUp" duration-ms="4" started-at="2019-01-16T04:54:15Z" data-provider="getData" finished-at="2019-01-16T04:54:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Year=1986.0, LN=Sharma, FN=Shekhar, BirthMonth=May, Runmode=Y, Mobile=9.999999999E9, Email=sharmashekhar8686, Day=17.0, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Runmode is set to NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Runmode is set to NO
at com.pge.hybrid.testcases.yahoosuite.YahooSignUp.YahooSignUp(YahooSignUp.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- YahooSignUp -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.pge.hybrid.testcases.yahoosuite.YahooSignUp@3aa9e816]" name="quit" is-config="true" duration-ms="803" started-at="2019-01-16T04:54:15Z" finished-at="2019-01-16T04:54:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.pge.hybrid.testcases.yahoosuite.YahooSignUp -->
    </test> <!-- Yahoo Sign up Test -->
    <test name="Yahoo Sign In Test" duration-ms="34831" started-at="2019-01-16T04:54:14Z" finished-at="2019-01-16T04:54:49Z">
      <class name="com.pge.hybrid.testcases.yahoosuite.YahooSignIn">
        <test-method status="PASS" signature="init()[pri:0, instance:com.pge.hybrid.testcases.yahoosuite.YahooSignIn@c39f790]" name="init" is-config="true" duration-ms="1218" started-at="2019-01-16T04:54:14Z" finished-at="2019-01-16T04:54:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="initTest()[pri:0, instance:com.pge.hybrid.testcases.yahoosuite.YahooSignIn@c39f790]" name="initTest" is-config="true" duration-ms="253" started-at="2019-01-16T04:54:15Z" finished-at="2019-01-16T04:54:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initTest -->
        <test-method status="FAIL" signature="yahooSignIn(java.util.Hashtable)[pri:0, instance:com.pge.hybrid.testcases.yahoosuite.YahooSignIn@c39f790]" name="yahooSignIn" duration-ms="31698" started-at="2019-01-16T04:54:15Z" data-provider="getData" finished-at="2019-01-16T04:54:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=shekhar, url=https://login.yahoo.com/, Password=1234, Runmode=Y, Browser=Mozilla}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.pge.hybrid.driver.DriverScript.executeKeywords(DriverScript.java:47)
at com.pge.hybrid.testcases.yahoosuite.YahooSignIn.yahooSignIn(YahooSignIn.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AssertionError: The following asserts failed:
Object Not Found yahoo_pwd_id
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.pge.hybrid.keywords.GenericKeywords.reportFailure(GenericKeywords.java:374)
at com.pge.hybrid.keywords.GenericKeywords.getObject(GenericKeywords.java:307)
at com.pge.hybrid.keywords.AppKeywords.yahooLogin(AppKeywords.java:61)
... 26 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- yahooSignIn -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.pge.hybrid.testcases.yahoosuite.YahooSignIn@c39f790]" name="quit" is-config="true" duration-ms="1584" started-at="2019-01-16T04:54:47Z" finished-at="2019-01-16T04:54:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.pge.hybrid.testcases.yahoosuite.YahooSignIn -->
    </test> <!-- Yahoo Sign In Test -->
  </suite> <!-- Yahoo Suite -->
  <suite name="My suite" duration-ms="0" started-at="2019-01-16T04:57:46Z" finished-at="2019-01-16T04:57:46Z">
    <groups>
    </groups>
  </suite> <!-- My suite -->
  <suite name="Gmail Suite" duration-ms="60416" started-at="2019-01-16T04:54:49Z" finished-at="2019-01-16T04:55:49Z">
    <groups>
    </groups>
    <test name="Gmail Sign Up Test" duration-ms="864" started-at="2019-01-16T04:54:49Z" finished-at="2019-01-16T04:54:49Z">
      <class name="com.pge.hybrid.testcases.gmailsuite.GmailSignUp">
        <test-method status="PASS" signature="init()[pri:0, instance:com.pge.hybrid.testcases.gmailsuite.GmailSignUp@6ad5c04e]" name="init" is-config="true" duration-ms="421" started-at="2019-01-16T04:54:49Z" finished-at="2019-01-16T04:54:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="SKIP" signature="GmailSignUp(java.util.Hashtable)[pri:0, instance:com.pge.hybrid.testcases.gmailsuite.GmailSignUp@6ad5c04e]" name="GmailSignUp" duration-ms="11" started-at="2019-01-16T04:54:49Z" data-provider="getData" finished-at="2019-01-16T04:54:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Runmode=Y, FN=Shekhar, LN=Sharma, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Runmode is set to NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Runmode is set to NO
at com.pge.hybrid.testcases.gmailsuite.GmailSignUp.GmailSignUp(GmailSignUp.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GmailSignUp -->
        <test-method status="PASS" signature="initTest()[pri:0, instance:com.pge.hybrid.testcases.gmailsuite.GmailSignUp@6ad5c04e]" name="initTest" is-config="true" duration-ms="0" started-at="2019-01-16T04:54:49Z" finished-at="2019-01-16T04:54:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initTest -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.pge.hybrid.testcases.gmailsuite.GmailSignUp@6ad5c04e]" name="quit" is-config="true" duration-ms="205" started-at="2019-01-16T04:54:49Z" finished-at="2019-01-16T04:54:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="initTest()[pri:0, instance:com.pge.hybrid.testcases.gmailsuite.GmailSignUp@6ad5c04e]" name="initTest" is-config="true" duration-ms="1" started-at="2019-01-16T04:54:49Z" finished-at="2019-01-16T04:54:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initTest -->
        <test-method status="SKIP" signature="GmailSignUp(java.util.Hashtable)[pri:0, instance:com.pge.hybrid.testcases.gmailsuite.GmailSignUp@6ad5c04e]" name="GmailSignUp" duration-ms="3" started-at="2019-01-16T04:54:49Z" data-provider="getData" finished-at="2019-01-16T04:54:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Runmode=Y, FN=Pankaj, LN=Jasrotia, Browser=Mozilla}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Runmode is set to NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Runmode is set to NO
at com.pge.hybrid.testcases.gmailsuite.GmailSignUp.GmailSignUp(GmailSignUp.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GmailSignUp -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.pge.hybrid.testcases.gmailsuite.GmailSignUp@6ad5c04e]" name="quit" is-config="true" duration-ms="193" started-at="2019-01-16T04:54:49Z" finished-at="2019-01-16T04:54:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.pge.hybrid.testcases.gmailsuite.GmailSignUp -->
    </test> <!-- Gmail Sign Up Test -->
    <test name="Gmail Sign In Test" duration-ms="60416" started-at="2019-01-16T04:54:49Z" finished-at="2019-01-16T04:55:49Z">
      <class name="com.pge.hybrid.testcases.gmailsuite.GmailLogin">
        <test-method status="PASS" signature="init()[pri:0, instance:com.pge.hybrid.testcases.gmailsuite.GmailLogin@2b80d80f]" name="init" is-config="true" duration-ms="329" started-at="2019-01-16T04:54:49Z" finished-at="2019-01-16T04:54:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="initTest()[pri:0, instance:com.pge.hybrid.testcases.gmailsuite.GmailLogin@2b80d80f]" name="initTest" is-config="true" duration-ms="18" started-at="2019-01-16T04:54:49Z" finished-at="2019-01-16T04:54:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initTest -->
        <test-method status="FAIL" signature="gmaillogin(java.util.Hashtable)[pri:0, instance:com.pge.hybrid.testcases.gmailsuite.GmailLogin@2b80d80f]" name="gmaillogin" duration-ms="58887" started-at="2019-01-16T04:54:49Z" data-provider="getData" finished-at="2019-01-16T04:55:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=sharmashekhar86, ExpectedResult=Loginsuccess, url=https://www.google.com/intl/en-GB/gmail/about/#, Password=hello, Runmode=Y, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.pge.hybrid.driver.DriverScript.executeKeywords(DriverScript.java:47)
at com.pge.hybrid.testcases.gmailsuite.GmailLogin.gmaillogin(GmailLogin.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AssertionError: The following asserts failed:
Object Not Found username_id
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.pge.hybrid.keywords.GenericKeywords.reportFailure(GenericKeywords.java:374)
at com.pge.hybrid.keywords.GenericKeywords.getObject(GenericKeywords.java:307)
at com.pge.hybrid.keywords.AppKeywords.gmailLogin(AppKeywords.java:32)
... 26 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- gmaillogin -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.pge.hybrid.testcases.gmailsuite.GmailLogin@2b80d80f]" name="quit" is-config="true" duration-ms="1179" started-at="2019-01-16T04:55:48Z" finished-at="2019-01-16T04:55:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.pge.hybrid.testcases.gmailsuite.GmailLogin -->
    </test> <!-- Gmail Sign In Test -->
  </suite> <!-- Gmail Suite -->
  <suite name="Facebook Suite" duration-ms="115937" started-at="2019-01-16T04:55:49Z" finished-at="2019-01-16T04:57:45Z">
    <groups>
    </groups>
    <test name="Facebook File Upload" duration-ms="751" started-at="2019-01-16T04:55:49Z" finished-at="2019-01-16T04:55:50Z">
      <class name="com.pge.hybrid.testcases.facebooksuite.UploadFiles">
        <test-method status="PASS" signature="init()[pri:0, instance:com.pge.hybrid.testcases.facebooksuite.UploadFiles@23223dd8]" name="init" is-config="true" duration-ms="575" started-at="2019-01-16T04:55:49Z" finished-at="2019-01-16T04:55:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="initTest()[pri:0, instance:com.pge.hybrid.testcases.facebooksuite.UploadFiles@23223dd8]" name="initTest" is-config="true" duration-ms="1" started-at="2019-01-16T04:55:50Z" finished-at="2019-01-16T04:55:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initTest -->
        <test-method status="SKIP" signature="UploadFile(java.util.Hashtable)[pri:0, instance:com.pge.hybrid.testcases.facebooksuite.UploadFiles@23223dd8]" name="UploadFile" duration-ms="27" started-at="2019-01-16T04:55:50Z" data-provider="getData" finished-at="2019-01-16T04:55:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=, ExpectedResult=, url=https://imgur.com/upload, filePath=C:\\HybridFramework\\HybridFramework\\Files\\FileUpload.exe, Password=, Runmode=Y, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Runmode is set to NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Runmode is set to NO
at com.pge.hybrid.testcases.facebooksuite.UploadFiles.UploadFile(UploadFiles.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UploadFile -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.pge.hybrid.testcases.facebooksuite.UploadFiles@23223dd8]" name="quit" is-config="true" duration-ms="145" started-at="2019-01-16T04:55:50Z" finished-at="2019-01-16T04:55:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.pge.hybrid.testcases.facebooksuite.UploadFiles -->
    </test> <!-- Facebook File Upload -->
    <test name="Facebook Sign In Test" duration-ms="115937" started-at="2019-01-16T04:55:49Z" finished-at="2019-01-16T04:57:45Z">
      <class name="com.pge.hybrid.testcases.facebooksuite.FacebookTest">
        <test-method status="PASS" signature="init()[pri:0, instance:com.pge.hybrid.testcases.facebooksuite.FacebookTest@649d209a]" name="init" is-config="true" duration-ms="249" started-at="2019-01-16T04:55:49Z" finished-at="2019-01-16T04:55:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="initTest()[pri:0, instance:com.pge.hybrid.testcases.facebooksuite.FacebookTest@649d209a]" name="initTest" is-config="true" duration-ms="9" started-at="2019-01-16T04:55:49Z" finished-at="2019-01-16T04:55:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initTest -->
        <test-method status="FAIL" signature="facebookLogin(java.util.Hashtable)[pri:0, instance:com.pge.hybrid.testcases.facebooksuite.FacebookTest@649d209a]" name="facebookLogin" duration-ms="60069" started-at="2019-01-16T04:55:49Z" data-provider="getData" finished-at="2019-01-16T04:56:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=shekhar_20_nice@yahoo.co.in, ExpectedResult=Success, url=https://www.facebook.com, filePath=C:\\HybridFramework\\HybridFramework\\Files\\FileUpload.exe, Password=, Runmode=Y, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.pge.hybrid.driver.DriverScript.executeKeywords(DriverScript.java:47)
at com.pge.hybrid.testcases.facebooksuite.FacebookTest.facebookLogin(FacebookTest.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AssertionError: The following asserts failed:
Object Not Found photo_vid_xpath
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.pge.hybrid.keywords.GenericKeywords.reportFailure(GenericKeywords.java:374)
at com.pge.hybrid.keywords.GenericKeywords.getObject(GenericKeywords.java:307)
at com.pge.hybrid.keywords.GenericKeywords.click(GenericKeywords.java:150)
... 26 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- facebookLogin -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.pge.hybrid.testcases.facebooksuite.FacebookTest@649d209a]" name="quit" is-config="true" duration-ms="1160" started-at="2019-01-16T04:56:49Z" finished-at="2019-01-16T04:56:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="initTest()[pri:0, instance:com.pge.hybrid.testcases.facebooksuite.FacebookTest@649d209a]" name="initTest" is-config="true" duration-ms="1" started-at="2019-01-16T04:56:51Z" finished-at="2019-01-16T04:56:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initTest -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.pge.hybrid.testcases.facebooksuite.FacebookTest@649d209a]" name="quit" is-config="true" duration-ms="165" started-at="2019-01-16T04:56:51Z" finished-at="2019-01-16T04:56:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="SKIP" signature="facebookLogin(java.util.Hashtable)[pri:0, instance:com.pge.hybrid.testcases.facebooksuite.FacebookTest@649d209a]" name="facebookLogin" duration-ms="0" started-at="2019-01-16T04:56:51Z" data-provider="getData" finished-at="2019-01-16T04:56:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=shekhar_20_nice@yahoo.co.in, ExpectedResult=Success, url=https://www.facebook.com, filePath=C:\\HybridFramework\\HybridFramework\\Files\\FileUpload.exe, Password=, Runmode=N, Browser=IE}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Runmode is set to NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Runmode is set to NO
at com.pge.hybrid.testcases.facebooksuite.FacebookTest.facebookLogin(FacebookTest.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- facebookLogin -->
        <test-method status="PASS" signature="initTest()[pri:0, instance:com.pge.hybrid.testcases.facebooksuite.FacebookTest@649d209a]" name="initTest" is-config="true" duration-ms="1" started-at="2019-01-16T04:56:51Z" finished-at="2019-01-16T04:56:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initTest -->
        <test-method status="FAIL" signature="AppScanSite(java.util.Hashtable)[pri:1, instance:com.pge.hybrid.testcases.facebooksuite.FacebookTest@649d209a]" name="AppScanSite" duration-ms="53167" started-at="2019-01-16T04:56:51Z" data-provider="getData" finished-at="2019-01-16T04:57:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=jsmith, url=http://demo.testfire.net/, Password=demo1234, Runmode=Y, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.pge.hybrid.driver.DriverScript.executeKeywords(DriverScript.java:47)
at com.pge.hybrid.testcases.facebooksuite.FacebookTest.AppScanSite(FacebookTest.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AssertionError: The following asserts failed:
Object Not Found SignIn_xpath
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.pge.hybrid.keywords.GenericKeywords.reportFailure(GenericKeywords.java:374)
at com.pge.hybrid.keywords.GenericKeywords.getObject(GenericKeywords.java:307)
at com.pge.hybrid.keywords.GenericKeywords.click(GenericKeywords.java:150)
... 26 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AppScanSite -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.pge.hybrid.testcases.facebooksuite.FacebookTest@649d209a]" name="quit" is-config="true" duration-ms="1098" started-at="2019-01-16T04:57:44Z" finished-at="2019-01-16T04:57:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.pge.hybrid.testcases.facebooksuite.FacebookTest -->
    </test> <!-- Facebook Sign In Test -->
  </suite> <!-- Facebook Suite -->
</testng-results>
